### ISSUE TITLE
Music Home Screen Section Not Showing Music Addons

### ISSUE THREAD

**Issue by TheClown1234** [gade01/Rapier#18]
When I try your skin with all included dependencies I noticed none of the music addons are listed.  I check installed addons and it says they are disabled and wont enable no matter what I do.  I have done a fresh install of kodi 15.1 and 15.2 RC3 with only one music addon installed.  Nothing else is installed other then your skin and 181fm music addon.  I hit music cat. button on home screen or addon and it goes black screen then hit esc to go back to home screen because nothing happens.  I have even enabled music library with no success.  I am lost on how to resolve this issue.  I tried disabling music category and creating a new one using music preset and the same happens also, black screen when selecting the addons listing.  Any suggestions?

**Comment by gade01** [comment]
I have answered your post in the forums.

If you're running the Rapier master branch on Kodi 15, this is your problem. The master branch is for Kodi 16 and the music library nodes are changed between Kodi 15 and 16.
