### ISSUE TITLE
caps fonts dont play well with cyrillic characters

### ISSUE THREAD

**Issue by stefansaraev** [gade01/Rapier#19]
hi there

thanks for making this great skin, I love it 

I noticed a small font issue, it seems that caps fonts dont play well with cyrillic characters, here some screenshots:

![1](https://cloud.githubusercontent.com/assets/758738/13495310/a1ce5b96-e152-11e5-8f25-6b34b3de3aba.jpg)
![2](https://cloud.githubusercontent.com/assets/758738/13495314/a625d84a-e152-11e5-8093-316296524bcd.png)

changing font to arial in appearance -> skin -> folts did not help

so, as a workaround, I replace default-caps / default-caps-bold / default-caps-light with default / default-bold / default-light fonts:

![3](https://cloud.githubusercontent.com/assets/758738/13495433/6b73e7a4-e153-11e5-9106-e2c8c09949aa.jpg)
![4](https://cloud.githubusercontent.com/assets/758738/13495417/53fc6e7a-e153-11e5-8f46-d11f9b4b2f58.jpg)

EDIT: using your testing repo with kodi 17.

**Comment by gade01** [comment]
Hi there.

Thanks a lot for the kind words :)

Just to let you know, I have taken note of this and will look into it at some point.

As a experiment, I tried to change all caps fonts to none caps fonts: in Font.xml, removing -caps from them and adding <style>uppercase</style>. This seemed to work, although it makes the font some pixels lower (which doesn't work for me).

Cheers
Gade

**Comment by stefansaraev** [comment]
it was fine with one of the new fonts (I dont remember which one as I dont use rapier now due to my very unusual set up). will close this. thank you!

**Comment by gade01** [comment]
Thanks for the feedback. Appreciate it!

**Comment by stefansaraev** [comment]
re-tested: Noto Sans is the font that works for me.

**Comment by gade01** [comment]
Thanks again.

And no worries at all. :)
