### ISSUE TITLE
Make wall view scroll up and down

### ISSUE THREAD

**Issue by MaikoHermans** [gade01/Rapier#22]
Make it available for people to choose if they want the wallview to be navigated horizontally or vertically

**Comment by gade01** [comment]
Not a bad idea. :)

I won't promise anything, but I might implement it sometime in the future. 

I'll leave this open as a reminder.

**Comment by gade01** [comment]
I gave it one more shot and actually ended up with a result I really like.

Added for Krypton: 9ed688f263ef41a5e4784959ce18fa317660c9f0
Added for Jarvis: 1ce81e20c85258ddd8f259c83c937dc645e1031e and fix 786522fa5a8ebc644fd48d7e7ed9a9879ee3a24d
Added for Isengard: 9d9cbd00960619c89dd5821c0684b407852f3eed

I'll push a new version to my development repo soon.

Thanks for suggesting the feature ;)

**Comment by MaikoHermans** [comment]
You beat me to it haha.
I posted how I went about displaying the option below the commit.
You can see it here https://github.com/gade01/Rapier/commit/1ce81e20c85258ddd8f259c83c937dc645e1031e

figured I would share it with you

**Comment by gade01** [comment]
Thanks for sharing. I'll look into it.
