### ISSUE TITLE
Possible bug in Kodi home screen background(showing icons)

### ISSUE THREAD

**Issue by MaikoHermans** [gade01/Rapier#23]
I just updated my skin by downloading the .zip file from the jarvis branch(since I'm using jarvis) after the #21 bug was fixed.
When I went back to the home screen I noticed that certain icons seem to be loading into the background.

Icons like the actor icon or genre icon etc. 
Here a screenshot of what it looks like exactly. They also change every few seconds or so.
Might be me messing something up. I did reboot kodi, however I didn't reboot the entire system

![image](https://cloud.githubusercontent.com/assets/6593958/15457035/e8464cd2-2081-11e6-8ae1-a3af1f7d2831.png)

EDIT:
My global background image setting is set as follows:
Single Image
Stock background
50% brightness

EDIT2:
After a system reboot the bug remained

**Comment by gade01** [comment]
That's because you have installed from Git.

The way the skin is designed, you have to install either from the official Kodi add-on repo or from my development repo.
