### ISSUE TITLE
KODI 18 LEIA RC5. Clean doesn't work

### ISSUE THREAD

**Issue by adamforeman** [gade01/Rapier#38]
I have setup a sub menu with UPDATE and CLEAN

UPDATE works as it should, however when you setup the same for CLEAN it doesn't execute the CLEAN code for some reason. 

Executing CLEAN from the SETTINGS, MEDIA menu is the only way to do it. 

Cheers

**Comment by gade01** [comment]
Thanks for reporting the issue.

Turns out the function has become case sensitive.

Fixed with 8aaa0457d7deaab5f404721f77847cda470941f4

It will be included in the next development and official release.

**Comment by gade01** [comment]
After the update, you need to add the same function again to your submenu.
