### ISSUE TITLE
Cannot Launch Video Addons From the Addons Home Screen.... and a couple of smaller issues

### ISSUE THREAD

**Issue by GavinDarkglider** [gade01/Rapier#39]
First off, Awesome skin...... love the work you have done here. The main issue I have found with this skin, is that on the addons home screen, you can select Video addons in the addons home screen widget, but you cant launch them. In the Music addons box underneath, everything works perfectly.

Second issues is that the visualization selector, doesnt populate the list. So if using a visualization like shadertoy, which has many options, you cannot change them, as there is nothing in the list.

All of this was tested with Kodi 18 rc5

**Comment by gade01** [comment]
Thanks for the kind words and support.

I have fixed the home screen add-on widgets. This will be included in the next development and official update.

Visualisations needs to be installed now, just like regular add-ons.
Click the "Get more..." button at the bottom og the dialog and install the visualisations you need.
