### ISSUE TITLE
less of an issues, more of a question for another project I am working on.

### ISSUE THREAD

**Issue by GavinDarkglider** [gade01/Rapier#40]
I am working on a service/addon for my nintendo switch build, and was curious about 2 things. number 1. can you point me to the block of code in the skin stuff that handles the drop down lists. This is the only skin that I have seen that does this.

and 2. how do the custom options for home screen work. You can set up custom views, but I have found them to be about useless. If I can work the code I want into the backend plugin in python, and then work the rest into the skin directly, that would be nice. 

I only ask, as the documentation is convoluted at best, and kodi isnt something I have spent a lot of time skinning, but I want  to be able to display realtime stats on things like the joycon connection status, and battery levels for controllers detected, etc. Might also add bluetooth/wifi setup stuff. Most of the backend code is easy enough, I am just not ontop of this guilib stuff for kodi, and not exactly sure how to interact with it. I can easily fill a basic list with data, but after that, I have no idea how to pass that back to the script as well...... But I digress, for now, I guess getting the UI xml right for what I am trying to do will be good for me.

**Comment by gade01** [comment]
> I am working on a service/addon for my nintendo switch build, and was curious about 2 things. number 1. can you point me to the block of code in the skin stuff that handles the drop down lists. This is the only skin that I have seen that does this.

Drop down dialogs are mostly made using custom dialogs, eg. custom_1113_ViewOptions.xml, where the dialog is called using ActivateWindow(1113). The background is dimmed when the dialog is active.

> and 2. how do the custom options for home screen work. You can set up custom views, but I have found them to be about useless. If I can work the code I want into the backend plugin in python, and then work the rest into the skin directly, that would be nice.

I'm not quite sure which parts exactly you are referring to?
Most customization are made using skin settings and skin strings.

I'd be more than happy to help out getting you on track with the skinning parts.

**Comment by gade01** [comment]
@GavinDarkglider 
I'm closing this issue.
Let me know if you're still interested at some point.
