### ISSUE TITLE
Bugs with Homizio Nova font on Spanish Translation

### ISSUE THREAD

**Issue by roliverosc** [gade01/Rapier#42]
Hi @gade i would like that updated spanish translation from transifex was available. I have corrected some bugs in the translation. If you want to check it out are available on my github also.

Other question, some characters are cut for menu text field size when the characters has accent mark. , Do is possible solve this bug in the layout of Rapier skin?. It happen with "homizio nova" font only.

Here the screenshot...

![img](https://i.imgur.com/BH1jBpC.png)

![img](https://i.imgur.com/UIUJ2jA.png)

![img](https://i.imgur.com/qctS3Mf.png)

Regards and thank you for this wonderful skin and sorry for my english.

PD: I think I'm late for an update XD

https://forum.kodi.tv/showthread.php?tid=304329&pid=2948044#pid2948044

**Comment by gade01** [comment]
Hi @roliverosc 

I have just updated latest translations from Transifex:  https://github.com/gade01/Rapier/commit/37021666a44e47b6c3bdf2434ac65c190cc3dbb6

Please check to see if your translation is correct: language/resource.language.es_es/strings.po

I will answer the other issues at the forums.

In the future, please don't write the exact same both here and at the forums.
